Repository Tan-Thai/JuraStina-Kalle-Park, pull requests merged in 2025-02, with the labels that each got.

#16 #3 - Defined Generic Tests
  Documentation.md
Labels: documentation

#20 Create robot framework file with test #4
  Generic-Test-Cases/__pycache__/variables.cpython-313.pyc
  Generic-Test-Cases/generic-keywords.robot
  Generic-Test-Cases/generic.robot
  Generic-Test-Cases/variables.py
Labels: enhancement

#19 Gitignore fixed for one user
  .gitignore
  Generic-Test-Cases/variables.py
Labels: bug

#21 docs(Generic.robot): Added documentation, tags and regions for multip…
  .idea/JuraStina-Kalle-Park.iml
  Generic-Test-Cases/generic.robot
  Generic-Test-Cases/variables.py
Labels: documentation

#28 Test cases for empty card, and VIP tickets instead of regular
  Generic-Test-Cases/generic-keywords.robot
  Generic-Test-Cases/generic.robot
  Generic-Test-Cases/variables.py
Labels: enhancement

#31 Test Cases for Kim/Family
  Kim-Family/testcases.robot
Labels: enhancement

#32 fix(Date Selection): Fixed date picker in dynamic calendar ui from JS
  Generic-Test-Cases/generic-keywords.robot
  Generic-Test-Cases/generic.robot
  Generic-Test-Cases/variables.py
  resources/global_files/weekday_helper.py
Labels: enhancement

#27 Refactor: Clean up and improvements of generic tests
  .idea/JuraStina-Kalle-Park.iml
  Generic-Test-Cases/generic-keywords.robot
  Generic-Test-Cases/generic.robot
  Generic-Test-Cases/variables.py
  resources/global_files/weekday_helper.py
Labels: documentation, enhancement, help wanted

#36 Snåla kalle - refactor/cleanup
  .gitignore
  Generic-Test-Cases/generic-keywords.robot
  Snåla-Kalle-Scenario/snåla-kalle-keywords.robot
  Snåla-Kalle-Scenario/snåla-kalle-variables.py
  Snåla-Kalle-Scenario/snåla-kalle.robot
Labels: documentation, help wanted

#37 kim family - refactor/cleanup
  Kim-Family/kim-keywords.robot
  Kim-Family/kim-test-cases.robot
Labels: documentation, help wanted

#38 Merge Snåla Kalle function into main
  .gitignore
  Generic-Test-Cases/generic-keywords.robot
  Kim-Family/__pycache__/kim-variables.cpython-313.pyc
  Snåla-Kalle-Scenario/snåla-kalle-keywords.robot
  Snåla-Kalle-Scenario/snåla-kalle-variables.py
  Snåla-Kalle-Scenario/snåla-kalle.robot
  resources/global_files/__pycache__/weekday_helper.cpython-313.pyc
Labels: Epic
